### ISSUE TITLE
[Win] Logs export doesn't work

### ISSUE THREAD

**Issue by trololo2305** [Privatix/privatix#106]
Actual for 0.21.0 version
After clicking on "Export all logs to a file" no script running but "Saving all logs" windows appears(screen below). No errors in Console.
![image (11)](https://user-images.githubusercontent.com/40266734/54813329-f5d92e80-4c95-11e9-8ef0-2aad8a5e2db8.png)
 Click on "Save" button, error message appears(screen below) 
![image (12)](https://user-images.githubusercontent.com/40266734/54813488-549ea800-4c96-11e9-8a33-1469df522457.png)

`Name                           Value
----                           -----
ALLUSERSPROFILE                C:\ProgramData
APPDATA                        C:\Users\S_D\AppData\Roaming
ChocolateyInstall              C:\ProgramData\chocolatey
ChocolateyLastPathUpdate       Fri Jan 18 15:29:19 2019
CommonProgramFiles             C:\Program Files\Common Files
CommonProgramFiles(x86)        C:\Program Files (x86)\Common Files
CommonProgramW6432             C:\Program Files\Common Files
COMPUTERNAME                   DESKTOP-1EON347
ComSpec                        C:\WINDOWS\system32\cmd.exe
DriverData                     C:\Windows\System32\Drivers\DriverData
FPS_BROWSER_APP_PROFILE_STRING Internet Explorer
FPS_BROWSER_USER_PROFILE_ST... Default
GOPATH                         C:\Users\S_D\go
GOROOT                         C:\Go\
HOMEDRIVE                      C:
HOMEPATH                       \Users\S_D
LOCALAPPDATA                   C:\Users\S_D\AppData\Local
LOGONSERVER                    \\DESKTOP-1EON347
NUMBER_OF_PROCESSORS           4
OneDrive                       C:\Users\S_D\OneDrive
OneDriveConsumer               C:\Users\S_D\OneDrive
OS                             Windows_NT
Path                           C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\Docker\Docker\Resources\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\PuTTY\;C:\ProgramData\chocolatey\...
PATHEXT                        .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL
PROCESSOR_ARCHITECTURE         AMD64
PROCESSOR_IDENTIFIER           Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
PROCESSOR_LEVEL                6
PROCESSOR_REVISION             5e03
ProgramData                    C:\ProgramData
ProgramFiles                   C:\Program Files
ProgramFiles(x86)              C:\Program Files (x86)
ProgramW6432                   C:\Program Files
PSModulePath                   C:\Users\S_D\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
PUBLIC                         C:\Users\Public
SESSIONNAME                    Console
SystemDrive                    C:
SystemRoot                     C:\WINDOWS
TEMP                           C:\Users\S_D\AppData\Local\Temp
TMP                            C:\Users\S_D\AppData\Local\Temp
USERDOMAIN                     DESKTOP-1EON347
USERDOMAIN_ROAMINGPROFILE      DESKTOP-1EON347
USERNAME                       AT
USERPROFILE                    C:\Users\S_D
windir                         C:\WINDOWS` 

Manually created dump via script
https://drive.google.com/file/d/1s9VmqayGWrt0kmJ1jV4FYE0aVIXaSWAm/view?usp=sharing

**Comment by drew2a** [comment]
Fixed in 1.0.1
