### ISSUE TITLE
failed to extract dapp

### ISSUE THREAD

**Issue by devalexandr** [Privatix/privatix#107]
### Prerequisites

Put an X between the brackets in corresponding line:

[ X ] Reproduced the problem in Agent Mode

[ X ] Reproduced the problem on Windows

[ X ] Reproduced the problem in the application, installed from binaries, provided by Privatix: https://github.com/Privatix/privatix/releases

[ X ] Followed all steps from the guide: https://privatix.atlassian.net/wiki/spaces/BVP/pages/270860384/How+to+download+it+and+give+it+a+try

[ X ] Checked that issue isn't already created: https://github.com/Privatix/privatix/issues

### Description
Installer closes with error:

![photo_2019-03-25_00-26-30](https://user-images.githubusercontent.com/31165861/54886055-aa40a380-4e94-11e9-81e5-8cb01c085d96.jpg)

### Versions

Version: 0.21.0

**Comment by drew2a** [comment]
Fixed in 1.0.1
