### ISSUE TITLE
agent's vpn is not work

### ISSUE THREAD

**Issue by devalexandr** [Privatix/privatix#119]
### Prerequisites

[ X ] Reproduced the problem in Agent Mode

[ X ] Reproduced the problem on Mac

[ X ] Reproduced the problem in the application, installed from binaries, provided by Privatix: https://github.com/Privatix/privatix/releases

[ X ] Followed all steps from the guide: https://privatix.atlassian.net/wiki/spaces/BVP/pages/270860384/How+to+download+it+and+give+it+a+try

[ X ] Checked that issue isn't already created: https://github.com/Privatix/privatix/issues

### Description

the agent seems to be ok, but vpn is not connecting to his offers
firewall on agent PC is disabled
Ports are reachable:

![Captura de Pantalla 2019-04-16 a la(s) 1 13 41 p  m](https://user-images.githubusercontent.com/31165861/56205905-b7941c80-6053-11e9-9bb1-97f12b33df56.png)
 
### Versions

Version: 0.21.1

### Environment

Agent logs:
https://drive.google.com/file/d/14Q-n1sGda2tAfdHJ8_FzaAsmXMCpY4vT/view?usp=sharing

Client logs:
https://drive.google.com/file/d/1UBos1qa22SoDq3zc3DsW7ERs6893RdpE/view?usp=sharing

**Comment by drew2a** [comment]
Can't reproduce.
Seems as vpn on the agent side is not running.
We will add additional logs to the next release.
