### ISSUE TITLE
[Ubuntu|Mac] Client and agent backend aren't started after restarting of PC

### ISSUE THREAD

**Issue by trololo2305** [Privatix/privatix#122]
1. Install application and run it
2. Close application and restart PC
3. After restart PC run application

Actual result: application can't be started(screen attached). After manual running of backend  *sudo machinectl status client/agent* everything is ok 

Logs https://drive.google.com/file/d/1Y8kpp75_02Xmmx_OPLWcv4zt9Jreuam5/view?usp=sharing

![2019-04-17_0949](https://user-images.githubusercontent.com/40266734/56348831-f222c400-61cf-11e9-93c8-e2d05ab11ac0.png)

**Comment by trololo2305** [comment]
Also issue is actual for MacOS

**Comment by drew2a** [comment]
Not reproduced
