### ISSUE TITLE
[Ubuntu|Win] Error message appears during uncooperative close 

### ISSUE THREAD

**Issue by trololo2305** [Privatix/privatix#132]
Please note: Despite of the error uncooperative close finish successfully. 
![2019-04-24_1926](https://user-images.githubusercontent.com/40266734/56676426-edc24380-66c6-11e9-85b4-ff23cf5e9bd2.png)
Logs
https://drive.google.com/file/d/16kdnVVNBVyHwEVlHn7Wq0k2XROEPrs67/view?usp=sharing

**Comment by drew2a** [comment]
Fixed in 1.0.1
