### ISSUE TITLE
[Windows_Korean] Agent installation failed

### ISSUE THREAD

**Issue by trololo2305** [Privatix/privatix#149]
![2019-05-15_1021](https://user-images.githubusercontent.com/40266734/57756131-48b1ee00-76fb-11e9-9077-41ee13513715.png)

Logs:
https://drive.google.com/file/d/1F-BHuwVktQLrQWv4TSHdL8ntzCGQAdHV/view?usp=sharing

**Comment by devalexandr** [comment]
the problem is appeared on last build of agent. 
the new logs: https://drive.google.com/file/d/17fVtQ0Jdx-BDhbAQ1dBRCagWKtxKwKOm/view?usp=sharing

Seems like the error with install tap interface is the same is on this issue: https://github.com/Privatix/privatix/issues/181
