### ISSUE TITLE
Fix notices

### ISSUE THREAD

**Issue by drew2a** [Privatix/privatix#151]
1. Don't hide notice automatically
2. Add `x` to every single notice

**Comment by gonzazoid** [comment]
![Screenshot 2019-05-28 at 13 48 33](https://user-images.githubusercontent.com/12472060/58472652-621d5600-814f-11e9-81ae-6e135e053f11.png)
![Screenshot 2019-05-28 at 13 48 39](https://user-images.githubusercontent.com/12472060/58472658-68133700-814f-11e9-9af0-3282182e7b4c.png)
