### ISSUE TITLE
Fix vulnerabilities

### ISSUE THREAD

**Issue by drew2a** [Privatix/privatix#154]
```npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN The package electron is included as both a dev and production dependency.

audited 8153 packages in 12.588s
found 3 vulnerabilities (2 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details```

**Comment by gonzazoid** [comment]
System? package-lock? Just now:
![Screenshot 2019-05-23 at 20 51 52](https://user-images.githubusercontent.com/12472060/58274974-b06fd500-7d9c-11e9-9bdd-b6af8cd899e0.png)

**Comment by gonzazoid** [comment]
and node.js version will be useful

**Comment by gonzazoid** [comment]
![Screenshot 2019-05-23 at 20 51 52](https://user-images.githubusercontent.com/12472060/58275304-61766f80-7d9d-11e9-9b11-5c378a6249c2.png)

**Comment by gonzazoid** [comment]
![Screenshot 2019-05-23 at 20 57 23](https://user-images.githubusercontent.com/12472060/58275351-78b55d00-7d9d-11e9-8a84-96433ff9e0bf.png)

**Comment by drew2a** [comment]
Everything is getting ok, after removing `./package-lock.json`
