### ISSUE TITLE
[Ubuntu] VPN. Installation failed on Ubuntu 18.0.4

### ISSUE THREAD

**Issue by trololo2305** [Privatix/privatix#170]
error: context deadline exceeded
object: {"Role":"agent","Path":"/opt/Privatix/agent","Source":"./app.tar.xz","Controller":{"DisplayName":"","EntryPoint":"dappctrl/dappctrl","Configuration":"dappctrl/dappctrl.config.json","Service":{"ID":"ctrl_3442e18c328ca345e34cd2fd1d45df5364ce5c17","GUID":"","Name":"","Command":"/opt/Privatix/agent/dappctrl/dappctrl","Args":["-config","/opt/Privatix/agent/dappctrl/dappctrl.config.json"],"AutoStart":false},"Settings":{"DB.Conn.dbname":"dappctrl","DB.Conn.host":"127.0.0.1","DB.Conn.port":"5433","DB.Conn.user":"postgres","PayAddress":"http://185.3.146.203:9000/v1/pmtChannel/pay","Report.userid":"be1c98e5a937b17204da5f76056e4ba79f0e38de0606c20700fe46c8b724ff9b","Role":"agent","SOMCServer.Addr":"localhost:5555","TorHostname":"2ufj2hiyxmbqd2po.onion","TorSocksListener":9099}},"Gui":{"DisplayName":"Privatix","EntryPoint":"dappgui/dapp-gui","Configuration":"dappgui/resources/app/settings.json","Service":null,"Settings":{"bugsnag.userid":"be1c98e5a937b17204da5f76056e4ba79f0e38de0606c20700fe46c8b724ff9b","wsEndpoint":"ws://localhost:8888/ws"}},"DBEngine":{"ServiceName":"","DB":{"Host":"127.0.0.1","User":"postgres","Password":"","DBName":"dappctrl","Port":"5433"},"Timeout":300},"TempPath":"/tmp/a6aa32f280dfd6e3478f438fb5c12de4","BackupPath":"","Version":"0.23.0","Tor":{"Hostname":"2ufj2hiyxmbqd2po.onion","HiddenServiceDir":"var/lib/tor/hidden_service","RootPath":"/opt/Privatix/agent","Config":"torrc","Addr":"127.0.0.1","SocksPort":9099,"VirtPort":80,"TargetPort":5555,"IsLinux":true},"UserID":"be1c98e5a937b17204da5f76056e4ba79f0e38de0606c20700fe46c8b724ff9b","Timeout":300,"OnlyCore":true,"Product":"","Verbose":false}
child process exited abnormally

**Comment by drew2a** [comment]
Fixed in 1.0.1
