### ISSUE TITLE
Add `openvpn-status.log` and `server.log` to new-dump.ps1

### ISSUE THREAD

**Issue by drew2a** [Privatix/privatix#180]

**Comment by sofabeat** [comment]
They are already included in dump. Cannot reproduce. Whole "log folder" is copied here: https://github.com/Privatix/privatix/blob/f689624837a7e87b7dde2109c0e8b539097e3c48/tools/dump_win/new-dump.ps1#L85

**Comment by drew2a** [comment]
Not reproduced
