### ISSUE TITLE
[Windows] When Client connected to Agent's VPN - internet is not working.

### ISSUE THREAD

**Issue by devalexandr** [Privatix/privatix#196]
### Prerequisites

Put an X between the brackets in corresponding line:

[ X ] Reproduced the problem in Agent Mode
[ X ] Reproduced the problem in Client Mode
[ ] Reproduced the problem on Ubuntu
[ X ] Reproduced the problem on Windows
[ ] Reproduced the problem on Mac
[ X ] Reproduced the problem in the application, installed from binaries, provided by Privatix: https://github.com/Privatix/privatix/releases
[ X ] Followed all steps from the guide: https://privatix.atlassian.net/wiki/spaces/BVP/pages/270860384/How+to+download+it+and+give+it+a+try
[ X ] Checked that issue isn't already created: https://github.com/Privatix/privatix/issues

### Description

When Client connected to Agent's VPN, internet stops working.

+ Offering accepted
+ VPN connected
+ 443, 9000 agent's ports are reachable on https://privatix.network/portcheck/
- But internet is not working through the agent's VPN. Websites and IP addresses are not reachable.

![42O2dv6 1](https://user-images.githubusercontent.com/31165861/62014936-c8eed800-b1af-11e9-81f0-6a02eaf54ed6.png)

Ping with VPN and without:
![42O2cuD 1](https://user-images.githubusercontent.com/31165861/62014940-d1471300-b1af-11e9-9ce0-ea5ac5d1bef6.png)

### Versions

Version: Beta v. 0.23.1

### Environment

Agent's logs: https://drive.google.com/file/d/1_Dxhv9Tm_2tIeuB2c2w-mgVd9W7GYRF2/view?usp=sharing 
Client's logs: https://drive.google.com/file/d/14fzZzVeudwvjoI3uCnHdP_sl-j1-X9pG/view?usp=sharing

**Comment by drew2a** [comment]
Fixed in 1.0.1
