### ISSUE TITLE
UncooperativeClose job fails

### ISSUE THREAD

**Issue by devalexandr** [Privatix/privatix#197]
### Prerequisites

Put an X between the brackets in corresponding line:

[ x ] Reproduced the problem in Client Mode

[ x ] Reproduced the problem on Windows

[ x ] Reproduced the problem in the application, installed from binaries, provided by Privatix: https://github.com/Privatix/privatix/releases

[ x ] Checked that issue isn't already created: https://github.com/Privatix/privatix/issues

### Description

clientPreUncooperativeClose job fails, probably because of the wrong config

### Versions

Version: 1.0.1

### Additional Information

topics and client logs:
https://privatix.slack.com/archives/CLQMRNQCB/p1565454683017800
https://privatix.slack.com/archives/CCN7CEF7C/p1565680268004600

jira issue:
https://privatix.atlassian.net/browse/BV-1579

**Comment by sofabeat** [comment]
https://github.com/Privatix/dappctrl/blob/72bface73064134e0816c091f11d0f360c72ca12/dappctrl.config.json#L174
300 seconds job start delay not aligned with `challenge_period` in prod.
