### ISSUE TITLE
[win] dapp-gui not works, if installed by non admin user

### ISSUE THREAD

**Issue by drew2a** [Privatix/privatix#30]
How to reproduce:

1. login to windows with non-admin user
2. run installer
3. give admin credentials for installation.

Expected:

1. Icon on desktop
2. dapp-gui can be executed

Actual:

1. No shortcut on desktop
2. Shortcut is created on admin’s account desktop instead.

# Proposed solution
1. Create UI API method, that allows to read and write UI settings (that currently stored in settings.json)
2. Use UI API method instead of settings.json

**Comment by drew2a** [comment]
@trololo2305 is it works properly?

**Comment by trololo2305** [comment]
Shortcut created on a desktop but after each running of application user gets a window for entering admin password
