### ISSUE TITLE
Add the "collect logs" feature.

### ISSUE THREAD

**Issue by drew2a** [Privatix/privatix#40]
To simplify users' log collection procedures, we have to develop the "collect logs" feature.

For users there will be a button on GUI side "collect logs". Depending on OS, dump win, ubuntu or mac scripts will be called.

https://github.com/Privatix/privatix/tree/master/tools

# Steps

1. Move "logs" link from "settings popup" to left menu
1. Rename "Export log to a file" button
1. Add "Export all logs to a file" button

![image](https://user-images.githubusercontent.com/13798583/50829486-3f90c900-1377-11e9-82fb-93c7ead3d0be.png)

This task is blocked by #41 

# CI

We should add the following files into the artefacts:

## mac
Files: 
* https://github.com/Privatix/privatix/blob/master/tools/dump_mac/dump_mac.sh

Folder:
* `util/dump/`

## win

Files:

* https://github.com/Privatix/privatix/blob/master/tools/dump_win/new-dump.ps1
* https://github.com/Privatix/privatix/blob/master/tools/dump_win/ps-runner.exe

Folder:
* `util/dump/`

## ubuntu

Files:
* https://github.com/Privatix/privatix/blob/master/tools/dump_ubuntu/dump_ubuntu.py

Folder:
* let's discuss

**Comment by trololo2305** [comment]
Tested on Mac
