### ISSUE TITLE
[Win] Channel terminated and contract "normally closed" when client doesn't use all traffic 

### ISSUE THREAD

**Issue by trololo2305** [Privatix/privatix#55]
Client doesn't use all available traffic  as channel automatically terminated and contract "normally closed"
Available traffic 1500MB Client use 1414MB

[Client 0115_0200dump.zip](https://github.com/Privatix/privatix/files/2759495/Client.0115_0200dump.zip)
[Agent 0115_0252dump.zip](https://github.com/Privatix/privatix/files/2759496/Agent.0115_0252dump.zip)
![2019-01-15_1238](https://user-images.githubusercontent.com/40266734/51179138-5ed6ab80-18cd-11e9-98df-dc65bec81270.png)

**Comment by drew2a** [comment]
@gonzazoid, should @trololo2305 recheck this issue?
