### ISSUE TITLE
[Win] Folder app.zip isn't deleted after  finish installation process

### ISSUE THREAD

**Issue by trololo2305** [Privatix/privatix#91]
![2019-03-07_1123](https://user-images.githubusercontent.com/40266734/53951265-c0014b00-40d6-11e9-878a-02033bc0f945.png)
Solution can be found in building logs 
![2019-03-07_1228](https://user-images.githubusercontent.com/40266734/53951558-64838d00-40d7-11e9-89ae-f9a5ff73fc9f.png)

**Comment by drew2a** [comment]
@trololo2305 please, check the solution

**Comment by trololo2305** [comment]
Fixed
cc: @drew2a @ubozov
