### ISSUE TITLE
Installer closes silently

### ISSUE THREAD

**Issue by Mahdi321** [Privatix/privatix#94]
### Prerequisites

Put an X between the brackets in corresponding line:

[ ] Reproduced the problem in Agent Mode

[X] Reproduced the problem in Client Mode

[X] Reproduced the problem on Ubuntu

[ ] Reproduced the problem on Windows

[ ] Reproduced the problem on Mac

[X ] Reproduced the problem in the application, installed from binaries, provided by Privatix: https://github.com/Privatix/privatix/releases

[X ] Followed all steps from the guide: https://privatix.atlassian.net/wiki/spaces/BVP/pages/270860384/How+to+download+it+and+give+it+a+try

[X ] Checked that issue isn't already created: https://github.com/Privatix/privatix/issues

### Description

Installer closes silently during downloading systemd_containers_ubuntu_x64_0.20.0.tar.xz 

**How often reproduced:** [100%]

### Versions

Version: 0.20.0

### Environment
[19-03-08 02-43-18.zip](https://github.com/Privatix/privatix/files/2944808/19-03-08.02-43-18.zip)

**Comment by drew2a** [comment]
Closed, due to moving installer to the new `go`–version (instead of old `python`)
